[package]
name = "owm-rs"
version = "0.4.1"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jiff = { version = "0.2.1", features = ["serde"] }
serde = { version = "1.0.145", features = ["derive"] }
